# Generated by Django 4.0.4 on 2022-05-02 07:31

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_project_alt_alter_service_alt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='body',
            new_name='body_fa',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='doing_time',
            new_name='doing_time_fa',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='end_time',
            new_name='end_time_fa',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='start_time',
            new_name='start_time_fa',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='title_fa',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='body',
            new_name='body_en',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='project',
            name='body_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='doing_time_en',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_time_en',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_time_en',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='body_fa',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='title_fa',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
