# Generated by Django 4.0.4 on 2022-04-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlegroup_article_alt_article_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='alt',
            field=models.CharField(default='alt', max_length=64),
        ),
        migrations.AlterField(
            model_name='articlegroup',
            name='alt',
            field=models.CharField(default='alt', max_length=64),
        ),
    ]
