# Generated by Django 4.0.4 on 2022-04-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_alt_alter_articlegroup_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlegroup',
            name='image',
            field=models.ImageField(upload_to='files/images/articles-group'),
        ),
    ]
