# Generated by Django 4.0.4 on 2022-05-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header_footer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Social media', 'verbose_name_plural': 'Social media'},
        ),
    ]
