# Generated by Django 4.0.4 on 2022-05-01 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('header_footer', '0002_alter_socialmedia_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='header_footer.header'),
        ),
    ]
