# Generated by Django 4.0.4 on 2022-05-01 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('header_footer', '0003_alter_header_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_text', models.CharField(max_length=120)),
                ('logo_alt', models.TextField(default='')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='files/images/logo')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='header_footer.menu')),
            ],
        ),
        migrations.DeleteModel(
            name='Header',
        ),
    ]
