# Generated by Django 4.0.4 on 2022-05-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header_footer', '0006_alter_menu_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='menu',
            name='title_fa',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
