# Generated by Django 3.2.8 on 2022-05-08 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header_footer', '0010_auto_20220508_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('page_visited', models.TextField()),
                ('event_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'verbose_name': 'User Activity', 'verbose_name_plural': 'User Activity'},
        ),
    ]
