# Generated by Django 3.2.8 on 2022-05-08 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header_footer', '0012_auto_20220508_1641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
