# Generated by Django 4.0.4 on 2022-04-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_alter_news_options_alter_news_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='alt',
            field=models.CharField(default='alt', max_length=128),
        ),
        migrations.AlterField(
            model_name='news',
            name='alt',
            field=models.CharField(default='alt', max_length=64),
        ),
        migrations.AlterField(
            model_name='partner',
            name='alt',
            field=models.CharField(default='alt', max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='alt',
            field=models.CharField(default='alt', max_length=128),
        ),
        migrations.AlterField(
            model_name='slider',
            name='alt',
            field=models.CharField(default='alt', max_length=128),
        ),
    ]
