# Generated by Django 4.0.4 on 2022-05-02 07:31

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_alter_comment_alt_alter_news_alt_alter_partner_alt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=0)),
                ('date', django_jalali.db.models.jDateField()),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='body_fa',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='title_fa',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='body',
            new_name='body_fa',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='title_fa',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='title_fa',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='title',
            new_name='title_fa',
        ),
        migrations.AddField(
            model_name='comment',
            name='body_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='title_en',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_en',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
