# Generated by Django 3.2.8 on 2022-05-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_visit_rename_body_comment_body_fa_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
